import re

mock_pagina = """
Rol de Procedimentos e Eventos em Saúde
(RN 465/2021, vigente a partir de 01/04/2021, e suas alterações)
RN
PROCEDIMENTO VIGÊNCIA OD AMB HCO HSO REF PAC DUT SUBGRUPO GRUPO CAPÍTULO
(alteração)
CONSULTAS, VISITAS HOSPITALARES OU
ACONSELHAMENTO GENÉTICO AMB HCO HSO REF PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
ATENDIMENTO/ACOMPANHAMENTO EM HOSPITAL-DIA PSIQUIÁTRICO (COM DIRETRIZ DE UTILIZAÇÃO) HCO HSO REF 109 PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
ATENDIMENTO INTEGRAL AO RECÉM-NASCIDO (SALA DE PARTO, BERÇÁRIO E UTI) HCO REF PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
ATENDIMENTO MÉDICO DO INTENSIVISTA EM UTI GERAL OU PEDIÁTRICA HCO HSO REF PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
ATENDIMENTO PEDIÁTRICO A GESTANTES (3º TRIMESTRE) AMB HCO REF PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
ATIVIDADE EDUCACIONAL PARA PLANEJAMENTO FAMILIAR AMB REF PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
ATIVIDADE EDUCATIVA EM SAÚDE BUCAL OD PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
ATIVIDADE EDUCATIVA EM ODONTOLOGIA PARA PAIS E/OU CUIDADORES DE PACIENTES COM NECESSIDADES CONSULTAS, VISITAS HOSPITALARES OU
OD PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ESPECIAIS ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
CONDICIONAMENTO EM ODONTOLOGIA (COM DIRETRIZ DE UTILIZAÇÃO) OD 86 PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
ESTABILIZAÇÃO DE PACIENTE POR MEIO DE CONTENÇÃO FÍSICA E/OU MECÂNICA OD PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
CONSULTA DE ACONSELHAMENTO PARA PLANEJAMENTO FAMILIAR AMB REF PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
CONSULTA COM ENFERMEIRO OBSTETRA OU OBSTETRIZ (COM DIRETRIZ DE UTILIZAÇÃO) AMB HCO REF 135 PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
CONSULTA/AVALIAÇÃO COM FISIOTERAPEUTA 541/2022 01/08/2022 AMB REF PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
CONSULTA MÉDICA AMB REF PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
CONSULTA ODONTOLÓGICA OD PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
CONSULTA ODONTOLÓGICA INICIAL OD PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
CONSULTA ODONTOLÓGICA DE URGÊNCIA OD PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
CONSULTA ODONTOLÓGICA PARA AVALIAÇÃO TÉCNICA DE AUDITORIA OD PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
CONSULTAS, VISITAS HOSPITALARES OU
CONSULTA/AVALIAÇÃO COM PSICÓLOGO 541/2022 01/08/2022 AMB REF PROCEDIMENTOS GERAIS PROCEDIMENTOS GERAIS
ACOMPANHAMENTO DE PACIENTES
Legenda: HCO: Seg. Hospitalar Com Obstetrícia PAC: Procedimento de Alta Complexidade
OD: Seg. Odontológica HSO: Seg. Hospitalar Sem Obstetrícia DUT: Diretriz de Utilização
AMB: Seg. Ambulatorial REF: Plano Referência 1
"""

# def test(texto):
#     legenda = {}
#     if texto:
#         # Ajuste na regex para capturar corretamente as abreviações e descrições
#         pares = re.findall(r'([A-Z]{2,})\s*:\s*([A-Za-zÀ-ÿ\s.]+)(?=[A-Z]{2,}\s*:|\s*$)', texto)
#         for abreviacao, definicao in pares:
#             legenda[abreviacao] = definicao.strip()
#
#     return legenda
#

def test(texto):
    resultado = {}
    if texto:
        # Encontra todas as ocorrências das chaves
        chaves = re.findall(r'[A-Z]{2,3}:', texto)
        if chaves:
            partes = re.split(r'[A-Z]{2,3}:', texto)
            for i in range(len(chaves)):
                chave = chaves[i][:-1]  # Remove o ":" do final da chave
                valor = partes[i + 1].strip()
                resultado[chave] = valor
    return resultado



print(test(mock_pagina))